#!/bin/bash
# Quick demonstration of v2.3.1 improvements

echo "Workflow v2.3.1 New Features Demo"
echo "=================================="
echo ""
echo "1. Edit Operations with Fuzzy Matching"
echo "   - Safe edits with pre-flight validation"
echo "   - Fuzzy matching when exact match fails"
echo "   - Diff preview before applying"
echo ""
echo "2. Documentation Template Validator"
echo "   - Check version consistency"
echo "   - Validate document structure"
echo "   - Check formatting issues"
echo ""
echo "3. Phase-Level Timing"
echo "   - Track phases within steps"
echo "   - Generate detailed timing reports"
echo ""
echo "Usage:"
echo "  source src/workflow/lib/edit_operations.sh"
echo "  safe_edit_file <file> <old> <new>"
echo ""
echo "  source src/workflow/lib/doc_template_validator.sh"
echo "  audit_documentation"
echo ""
echo "  source src/workflow/lib/metrics.sh"
echo "  start_phase_timer 1 'phase_name' 'Description'"
