#!/usr/bin/env bash
set -euo pipefail

################################################################################
# Step 1.5 Reporting Module
# Version: 1.0.0
# Purpose: Generate formatted coverage reports
################################################################################

# Generate detailed coverage report
# Args: $1 = report file, $2 = summary file, $3 = total APIs, $4 = undocumented count
generate_step1_5_coverage_report() {
    local report_file="$1"
    local summary_file="$2"
    local total_apis="$3"
    local undocumented="$4"
    
    local documented=$((total_apis - undocumented))
    local coverage=0
    if [[ $total_apis -gt 0 ]]; then
        coverage=$((100 * documented / total_apis))
    fi
    
    # Create summary report
    cat > "$summary_file" << EOF
# API Coverage Report - Step 1.5

**Date**: $(date '+%Y-%m-%d %H:%M:%S')
**Workflow Run**: ${WORKFLOW_RUN_ID:-unknown}

---

## Summary

| Metric | Value |
|--------|-------|
| **Total APIs** | ${total_apis} |
| **Documented** | ${documented} (${coverage}%) |
| **Undocumented** | ${undocumented} |
| **Threshold** | ${API_COVERAGE_THRESHOLD}% |
| **Status** | $(get_coverage_status "$coverage") |

---

## Coverage Breakdown

EOF
    
    # Add coverage status
    if [[ $coverage -ge ${API_COVERAGE_THRESHOLD} ]]; then
        cat >> "$summary_file" << EOF
✅ **PASS**: Coverage ${coverage}% meets threshold ${API_COVERAGE_THRESHOLD}%

Your project has excellent API documentation coverage!

EOF
    else
        local needed=$(calculate_required_apis "$total_apis" "$documented" "${API_COVERAGE_THRESHOLD}")
        cat >> "$summary_file" << EOF
⚠️  **WARNING**: Coverage ${coverage}% is below threshold ${API_COVERAGE_THRESHOLD}%

**Action Required**: Document ${needed} more API(s) to reach threshold.

EOF
    fi
    
    # Add undocumented APIs list
    if [[ -f "$report_file" ]] && [[ -s "$report_file" ]]; then
        cat >> "$summary_file" << EOF

## Undocumented APIs

\`\`\`
$(cat "$report_file")
\`\`\`

EOF
    fi
    
    # Add recommendations
    cat >> "$summary_file" << EOF

## Recommendations

EOF
    
    if [[ $undocumented -gt 0 ]]; then
        cat >> "$summary_file" << EOF
1. **Document High-Priority APIs**: Focus on public APIs with the most usage
2. **Use Inline Documentation**: Add JSDoc, docstrings, or comments directly in code
3. **Update API Docs**: Ensure \`docs/\` contains API reference documentation
4. **Run AI Suggestions**: Enable \`API_COVERAGE_AI_SUGGESTIONS=true\` for auto-generated drafts

EOF
    else
        cat >> "$summary_file" << EOF
✅ All APIs are documented! Maintain this standard for new code.

EOF
    fi
    
    # Add footer
    cat >> "$summary_file" << EOF

---

*Generated by AI Workflow Automation - Step 1.5 API Coverage Report*
EOF
    
    return 0
}

# Format undocumented APIs by file
# Args: $1 = report file
format_undocumented_by_file() {
    local report_file="$1"
    
    if [[ ! -f "$report_file" ]] || [[ ! -s "$report_file" ]]; then
        echo "No undocumented APIs found"
        return 0
    fi
    
    # Group by file and count
    awk -F: '{print $1}' "$report_file" | sort | uniq -c | sort -rn | while read -r count file; do
        echo "  ${file}: ${count} undocumented API(s)"
        grep "^${file}:" "$report_file" | sed 's/^[^:]*: /    - /' | head -5
        local total=$(grep -c "^${file}:" "$report_file" || echo 0)
        if [[ $total -gt 5 ]]; then
            echo "    ... and $((total - 5)) more"
        fi
    done
}

# Export functions
export -f generate_step1_5_coverage_report
export -f format_undocumented_by_file
